# Generated by Django 4.2.2 on 2023-06-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_list', '0002_alter_todoitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='titles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
