# Generated by Django 4.2.2 on 2023-06-16 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_list', '0003_tag_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='titles',
        ),
    ]
