# Generated by Django 4.2.2 on 2023-06-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_list', '0007_rename_full_name_user_name_user_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
